# Generated by Django 2.2.8 on 2020-05-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='quantity_size',
        ),
    ]
