# Generated by Django 2.2.8 on 2020-05-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200504_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity_size',
            new_name='quantities_size',
        ),
    ]
