# Generated by Django 2.2.8 on 2020-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200504_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreview',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='item/review/img/'),
        ),
    ]
