# Generated by Django 2.2.8 on 2020-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label_color',
            field=models.CharField(blank=True, choices=[('P', 'primary-color'), ('S', 'secondary-color'), ('D', 'danger-color')], max_length=1, null=True),
        ),
    ]
