# Generated by Django 2.2.8 on 2020-05-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='user/img/default-user-profile-img.png', upload_to='user/img/'),
        ),
    ]
