# Generated by Django 2.2.8 on 2020-04-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200422_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15.jpg', upload_to='item/img/'),
        ),
    ]
