# Generated by Django 2.2.8 on 2020-05-01 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200501_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('first_address', models.TextField()),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('country', models.TextField()),
                ('region', models.TextField()),
                ('city', models.TextField()),
                ('zip_code', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
