# Generated by Django 2.2.8 on 2020-03-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200328_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_items',
            new_name='order_items',
        ),
    ]
