# Generated by Django 2.2.8 on 2020-03-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200328_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(default='https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15.jpg', max_length=100),
        ),
    ]
