# Generated by Django 2.2.8 on 2020-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200329_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirts'), ('SW', 'Sport Wears'), ('O', 'Outwears'), ('A', 'Accessories'), ('CW', 'Casual Wears')], max_length=2),
        ),
    ]
