# Generated by Django 2.2.8 on 2020-04-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_continent_country_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street',
        ),
    ]
