# Generated by Django 2.2.8 on 2020-04-14 23:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200414_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
    ]
