# Generated by Django 2.2.8 on 2020-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
