# Generated by Django 2.2.8 on 2020-05-01 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CheckoutInfo'),
        ),
        migrations.DeleteModel(
            name='CheckoutInfo',
        ),
    ]
